[package]
name = "what_stream"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
attohttpc = { version = "0.16.0", features = ["json"] }
serde = { version = "1.0.117", features = ["derive"] }
time = "0.2.22"
